** Data Base
BLOCK: ${DESIGN_NAME}
IGNORE_CAPACITANCE: ALL
MOS_GATE_CAPACITANCE: 0.0
XREF: YES
NET_TYPE: schematic

** Technology
* FILE_NXTGRD = $INTEL_PDK/extraction/starrc/techfiles/$LAYERSTACK/<SKEW>.nxtgrd
* SKEW = See release notes for available skews.
TCAD_GRD_FILE: ${STARRC_NXTGRD_FILE}
MAPPING_FILE: ${STARRC_MAPPING_FILE}
MAGNIFICATION_FACTOR: 1
MAGNIFY_DEVICE_PARAMS: NO
REPORT_SMIN_VIOLATION: YES

** General
VERBOSE: NO
* Set VALUE_STARRC_CASESENSE to YES|NO
CASE_SENSITIVE: YES
STAR_DIRECTORY: star
BUS_BIT: []

** Accuracy
EXTRACTION: RC

** VALUE_TEMPERATURE to be referenced from userguide.
OPERATING_TEMPERATURE: ${STARRC_TEMPERATURE}
EXTRACT_VIA_CAPS: YES

** Nets to Extract
NETS: *
POWER_NETS: VCC* vcc* VDD* vdd* VSS* vss*
* VALUE_POWER_EXTRACT should be set based on project
POWER_EXTRACT: DEVICE_LAYERS  

** Pin Handling
SHORT_PINS: YES
INSTANCE_PORT: CONDUCTIVE CELL * INST * PORT *
MARKER_GENERATION: USER
TRANSLATE_RETAIN_BULK_LAYERS: YES
PIN_CUT_LOCATION_CENTER: YES

** Via Handling
* FILE_CUSTOM_VIACOV = $INTEL_PDK/extraction/starrc/techfiles/$LAYERSTACK/<SKEW>.via_coverage.custom
VIA_COVERAGE_OPTION_FILE: ${INTEL_PDK}/extraction/starrc/techfiles/$LAYERSTACK/tttt.via_coverage.custom
KEEP_VIA_NODES: YES
MERGE_VIAS_IN_ARRAY: NO
TRANSLATE_VIA_LAYERS: YES
RV_VIA_EXTRACT_PROPERTY: SAVL SAVC

** RV Related
* VALUE_NODE_MODE = NODE or NONE or NODE RES
EXTRA_GEOMETRY_INFO: NONE

** Reduction
REDUCTION: NO
POWER_REDUCTION: NO
REDUCTION_MAX_DELAY_ERROR: 1.0e-15

** Threshold
GROUND_CROSS_COUPLING: NO
COUPLING_ABS_THRESHOLD: 0.0
COUPLING_REL_THRESHOLD: 0.0
COUPLE_TO_GROUND: NO
* NETLIST_MINCAP_THRESHOLD: 0.0
* NETLIST_MINRES_HANDLING: SHORT
* NETLIST_MINRES_THRESHOLD: 0.001

** Fill Track handling
METAL_FILL_POLYGON_HANDLING: FLOATING
TRANSLATE_FLOATING_AS_FILL: YES
REMOVE_FLOATING_NETS: YES
REMOVE_DANGLING_NETS: YES

** Netlist Options
NETLIST_CONNECT_SECTION: YES
NETLIST_NODE_SECTION: YES
NETLIST_NODENAME_NETNAME: YES
NETLIST_UNSCALED_COORDINATES: YES
NETLIST_CONNECT_OPENS: !*

* VALUE_TAILCOMMENTS = YES or NO
* Change VALUE_TAILCOMMENTS based on RV setting and Reduction
NETLIST_TAIL_COMMENTS: NO
* VALUE_FORMAT = spf or spef or oa
NETLIST_FORMAT: spf
NETLIST_FILE: ${STARRC_SPF}
NETLIST_TYPE: RCg *
NETLIST_SELECT_NETS: * 
NETLIST_COUPLE_UNSELECTED_NETS: IDEAL
NETLIST_NAME_MAP: YES
NETLIST_PASSIVE_PARAMS: YES
NETLIST_DEVICE_LOCATION_ORIENTATION: YES
NETLIST_PRECISION: 8
ANGSTROM_DBUNIT_SUFFIX: NO

** Spice File Options
NETLIST_IDEAL_SPICE_FILE: ${DESIGN_NAME}.sp
NETLIST_IDEAL_SPICE_HIER: YES
NETLIST_IDEAL_SPICE_TYPE: SCHEMATIC
*SPICE_SUBCKT_FILE: <LIST_SUBCKT_FILES>

** Xtractor options
Mdb: 1357531

** CCP
CCP_EXTRACTION_FILE: ../ccp.cmd
CCP_ANNOTATION_FILE: YES

** S/D Swapping in upper case
XREF_SWAP_MOS_SD_PROPERTY: SNDI SIDN
XREF_SWAP_MOS_SD_PROPERTY: SHRD SHRS
XREF_SWAP_MOS_SD_PROPERTY: SNDF SFDN
XREF_SWAP_MOS_SD_PROPERTY: SFDI SIDF
XREF_SWAP_MOS_SD_PROPERTY: PES PED

** S/D Swapping
XREF_SWAP_MOS_SD_PROPERTY: sndi sidn
XREF_SWAP_MOS_SD_PROPERTY: shrd shrs
XREF_SWAP_MOS_SD_PROPERTY: sndf sfdn
XREF_SWAP_MOS_SD_PROPERTY: sfdi sidf
XREF_SWAP_MOS_SD_PROPERTY: pes ped

** BLACKBOXING
CELL_TYPE: LAYOUT
SKIP_CELLS: !*


** Calibre-StarRC flow
LVS_EXTRACTION_REPORT_FILE: ../../calibre/lvs/CCI/lvs_report_file
CALIBRE_QUERY_FILE: ../../calibre/lvs/query.cmd

** Temperature Sensitive flow
* VALUE_MODE_TEMP_SENSE = YES or NO
TEMPERATURE_SENSITIVITY: YES


**** These are commands/options meant only for Netlist-based Reliability Verification
** Refer Reliability flow documentation on the use of these options
*<ENABLE_RV_OPTIONS>DETECT_FUSE: YES
*<ENABLE_RV_OPTIONS>PRINT_RV_FUSE: YES
*<ENABLE_RV_OPTIONS>RV_PRINT_RESISTOR_TYPE: YES
*<ENABLE_RV_OPTIONS>PRINT_CURRENT_DIRECTION: YES
*<ENABLE_RV_OPTIONS>PRINT_SILICON_INFO: YES
*<ENABLE_RV_OPTIONS>SHORT_PINS: NO
*<ENABLE_RV_OPTIONS>REMOVE_DANGLING_NETS: NO
*<ENABLE_RV_TEMPLATE_OPTIONS>INSTANCE_PORT: CONDUCTIVE MULTIPLE SUFFIXED CELL * INST * PORT *
*<ENABLE_RV_TEMPLATE_OPTIONS>INSTANCE_PORT: SUPERCONDUCTIVE CELL b811tsv2ptn6000xnxunx b811tsv1ptn6000xnxunx
*<ENABLE_RV_TEMPLATE_OPTIONS>NETLIST_RENAME_PORTS: XYI
*<ENABLE_RV_TEMPLATE_OPTIONS>PLACEMENT_INFO_FILE: YES
*<ENABLE_RV_TEMPLATE_OPTIONS>PLACEMENT_INFO_FILE_NAME: <VALUE_TOPCELL>.xyv
*<ENABLE_RV_TEMPLATE_OPTIONS>NETLIST_POSTPROCESS_COMMAND: perl -ane '{s/_x_?\d+y_?\d+_\d+/ /ig; print $_}'

** Distributed processing
NUM_CORES: 10
*<ENABLE_DISTRIBUTED_PROCESSING>STARRC_DP_STRING: <SSH_STRING_STARRC_JOB_DP>

** Simultaneous Multi Corner flow
*<ENABLE_SMC_FLOW>CORNERS_FILE: corners.defines
*<ENABLE_SMC_FLOW>SIMULTANEOUS_MULTI_CORNER: YES
*<ENABLE_SMC_FLOW>SELECTED_CORNERS: <SELECTED_CORNER_LIST>

*<ENABLE_SMC_FLOW>NETLIST_SMC_FORMULA: <VALUE_SMCFORMULA>

** OA extracted view options
*<OA_EXTRACTED_VIEW_ENABLED>HIERARCHICAL_SEPARATOR: |
*<OA_EXTRACTED_VIEW_ENABLED>OA_DEVICE_MAPPING_FILE: <FILE_OA_DEVICE_DFII_MAP>
*<OA_EXTRACTED_VIEW_ENABLED>OA_LAYER_MAPPING_FILE: oalayers.starrc.map
*<OA_EXTRACTED_VIEW_ENABLED>OA_LIB_DEF: cds.lib
*<OA_EXTRACTED_VIEW_ENABLED>OA_LIB_NAME: <VALUE_LIBNAME>
*<OA_EXTRACTED_VIEW_ENABLED>OA_VIEW_NAME: <VALUE_OAEXTVIEW_NAME>
*<OA_EXTRACTED_VIEW_ENABLED>OA_REMOVE_DUPLICATE_PORTS: YES
*<OA_EXTRACTED_VIEW_ENABLED>OA_MARKER_SIZE: 0.01
*<OA_EXTRACTED_VIEW_ENABLED>OA_INSTANCE_PIN_NAME: symbol
*<OA_EXTRACTED_VIEW_ENABLED>OA_SKIPCELL_MAPPING_FILE: oa_skipcells.map
*<OA_EXTRACTED_VIEW_ENABLED>NETLIST_GROUND_NODE_NAME: gnd!
*<OA_EXTRACTED_VIEW_ENABLED>OA_BUS_BIT: <>
*<OA_EXTRACTED_VIEW_ENABLED>OA_CDLOUT_RUNDIR: .

** Skip pcell flow
** In normal PV mode please use DISABLE_IN_RV_MODE tagged commands and remove ENABLE_RV_OPTIONS tagged commands.
** But for RV runs please set runset env _drRFRV or DR_RFRV, use ENABLE_RV_OPTIONS  tagged commands and remove DISABLE_IN_RV_MODE commands tagged commands
*<DISABLE_IN_RV_MODE>SKIP_PCELLS:  *b88xp_dcps2p_unit* *b88xp_mfc_unit* *b88xp_tfr_unit* *b88xp_tfr_fill* *b88xp_tfrdacbody* *b88xp_tfrdaccon* *b88xp_mim* *b88x_ednrf_* *b88x_edprf_* *b88xp_nrfhp_* *b88xp_prfhp_* *b88xp_ndnwrfhp_*  *cap_hd* *b88xp_poly_* *b88xp_polynwl_* *b88xp_polypara_* *b88xp_polyparanwl_* *b88xp_polyser_* *b88xp_polysernwl_* *b88xp_gcn_* *b88xp_gcnnwl_* *b88xp_gcnpara_* *b88xp_gcnparanwl_* *b88xp_gcnser_* *b88xp_gcnsernwl_* *b88xp_nrf_* *b88xp_nlvtrf_* *b88xp_ntgrf_* *b88xp_prf_* *b88xp_plvtrf_* *b88xp_ptgrf_* *b88xp_nrfll_* *b88xp_nlvtrfll_* *b88xp_prfll_* *b88xp_plvtrfll_* *b88xp_nrfhyp120_* *b88xp_nrfhyp160_*
*<ENABLE_RV_OPTIONS>SKIP_PCELLS:  *b88xp_dcps2p_unit* *b88xp_mfc_unit* *b88xp_tfr_unit* *b88xp_tfr_fill* *b88xp_tfrdacbody* *b88xp_tfrdaccon* *b88xp_mim* *cap_hd* *b88xp_poly_* *b88xp_polynwl_* *b88xp_polypara_* *b88xp_polyparanwl_* *b88xp_polyser_* *b88xp_polysernwl_* *b88xp_gcn_* *b88xp_gcnnwl_* *b88xp_gcnpara_* *b88xp_gcnparanwl_* *b88xp_gcnser_* *b88xp_gcnsernwl_*
SKIP_PCELL_LAYERS_FILE: ../skip_pcell_layers_file
COUPLE_TO_PCELL_PINS: YES KEEP_CG
